# Generated by Django 3.2.8 on 2021-10-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
